export enum WorkoutType {
  BIKE = 'BIKE',
  INTERVAL = 'INTERVAL',
  CONTINUOUS = 'CONTINUOUS',
  ELEVATION = 'ELEVATION',
  STRENGTH = 'STRENGTH',
  ACTIVATION = 'ACTIVATION',
  COMPETITION = 'COMPETITION',
  REST = 'REST',
  QUALITY = 'QUALITY',
}
